CREATE TABLE IF NOT EXISTS cities(
  wiki_id VARCHAR(20) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  country VARCHAR(100) NOT NULL,
  population BIGINT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL
);